### ISSUE TITLE
support rate limit

### ISSUE THREAD

**Issue by askintution** [langchain-ai/streamlit-agent#4]
openai account has rate limit. The application will output error.
anyway to fix this issue?

**Comment by Muhtasham** [comment]
maybe you can try this, described [here](https://github.com/BerriAI/reliableGPT)

> When a request to your llm app fails, reliableGPT handles it by:
> 
> Retrying with an alternate model - GPT-4, GPT3.5, GPT3.5 16k, text-davinci-003
> Retrying with a larger context window model for Context Window Errors
> Sending a Cached Response (using semantic similarity)
> Retry with a fallback API key for Invalid API Key errors

**Comment by sfc-gh-jcarroll** [comment]
Hi @askintution , minimally you can do try/catch on the agent.run call to handle the error (such as printing a friendly `st.error()` or having the assistant respond with a useful message)

```python
try:
    response = agent.run(user_input, callbacks=[st_callback])
except: # or filter to certain errors you know about like openai.AuthenticationError
    st.error("Encountered an error, try again later")
```

LangChain also has some throttling and automatic retry support for the case where rate limit is due to frequent requests. It's outside the scope of reference implementations in this repository but you can find ideas in LangChain documentation and user issues 😄
